# Generated by Django 5.0.3 on 2024-03-05 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('names', models.CharField(max_length=50)),
                ('lastnames', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('id_user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_role')),
            ],
        ),
    ]
