# Generated by Django 5.0.3 on 2024-03-05 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('report_datetime', models.DateTimeField()),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('id_report_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report_status')),
            ],
        ),
    ]
