# Generated by Django 5.0.3 on 2024-03-05 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_document_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_request', models.DateField()),
                ('date_final_status', models.DateField()),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responder_admin', to='account.account')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesting_user', to='account.account')),
                ('id_request_document_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.request_document_status')),
            ],
        ),
    ]
