# Generated by Django 5.0.3 on 2024-03-08 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_document',
            name='id_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responder_admin', to='account.account'),
        ),
    ]
