# Generated by Django 5.0.3 on 2024-03-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_request_document_id_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_document',
            name='date_final_status',
            field=models.DateField(blank=True, null=True),
        ),
    ]
